apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Values.ingress.name }}"
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "{{ .Values.domainName }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: "{{ .Values.app.name }}"
          servicePort: {{ .Values.app.port }}
